import 'package:fb_core/fb_core.dart';
import 'package:flutter/widgets.dart';

/// UI copy in Arabic (default) and English. Product names come from data.
class S {
  const S(this.locale);
  final String locale;
  bool get isAr => locale == 'ar';

  static S of(BuildContext context) => S(Localizations.localeOf(context).languageCode);

  String t(String key) => (_strings[key] ?? const {})[locale] ?? (_strings[key] ?? const {})['ar'] ?? key;
  String call(String key) => t(key);

  String money(Money? m) => m == null ? t('price_by_selection') : m.format(locale);

  String orderStatus(OrderStatus s) => t('status_${s.name}');

  String error(FbError e) => _strings.containsKey('err_${e.code}') ? t('err_${e.code}') : t('err_UNKNOWN');

  static const _strings = <String, Map<String, String>>{
    'tagline': {'ar': 'فاكهتك على مزاجك', 'en': 'Fruit, your way'},
    'skip': {'ar': 'تخطٍّ', 'en': 'Skip'},
    'continue': {'ar': 'متابعة', 'en': 'Continue'},
    'retry': {'ar': 'إعادة المحاولة', 'en': 'Try again'},
    'cancel': {'ar': 'إلغاء', 'en': 'Cancel'},
    'save': {'ar': 'حفظ', 'en': 'Save'},
    'close': {'ar': 'إغلاق', 'en': 'Close'},
    'back': {'ar': 'رجوع', 'en': 'Back'},
    'choose_language': {'ar': 'اختر لغتك', 'en': 'Choose your language'},
    'choose_branch': {'ar': 'اختر الفرع', 'en': 'Choose a branch'},
    'choose_branch_sub': {'ar': 'الأسعار والتوفر تختلف من فرع لآخر', 'en': 'Prices and availability vary by branch'},
    'search_branches': {'ar': 'ابحث باسم المنطقة', 'en': 'Search by area'},
    'branch_pending': {'ar': 'بانتظار اعتماد بيانات الفرع', 'en': 'Branch details awaiting approval'},
    'branch_closed': {'ar': 'الفرع مغلق حالياً', 'en': 'Branch is closed now'},
    'branch_open': {'ar': 'مفتوح', 'en': 'Open'},
    'hours_unknown': {'ar': 'أوقات العمل بانتظار الاعتماد', 'en': 'Opening hours awaiting approval'},
    'no_branches_match': {'ar': 'لا يوجد فرع بهذا الاسم', 'en': 'No branch matches'},
    'how_to_receive': {'ar': 'كيف تحب تستلم طلبك؟', 'en': 'How would you like your order?'},
    'pickup': {'ar': 'استلام من الفرع', 'en': 'Pickup'},
    'delivery': {'ar': 'توصيل', 'en': 'Delivery'},
    'pickup_sub': {'ar': 'جاهز خلال دقائق', 'en': 'Ready in minutes'},
    'delivery_sub': {'ar': 'لباب بيتك', 'en': 'To your door'},
    'delivery_unavailable': {'ar': 'التوصيل غير مفعّل حتى اعتماد الرسوم ومنطقة التغطية', 'en': 'Delivery is off until fees and coverage are approved'},
    'greeting': {'ar': 'وش مزاجك اليوم؟', 'en': "What's your mood today?"},
    'search_hint': {'ar': 'ابحث عن عصير، سلطة، آيس كريم…', 'en': 'Search juices, fruit salads, ice cream…'},
    'categories': {'ar': 'الأقسام', 'en': 'Categories'},
    'see_all': {'ar': 'عرض الكل', 'en': 'See all'},
    'new_items': {'ar': 'الجديد', 'en': "What's new"},
    'best_sellers': {'ar': 'الأكثر طلباً', 'en': 'Best sellers'},
    'new_badge': {'ar': 'جديد', 'en': 'New'},
    'menu': {'ar': 'المنيو', 'en': 'Menu'},
    'home': {'ar': 'الرئيسية', 'en': 'Home'},
    'offers': {'ar': 'العروض', 'en': 'Offers'},
    'orders': {'ar': 'طلباتي', 'en': 'Orders'},
    'account': {'ar': 'حسابي', 'en': 'Account'},
    'favorites': {'ar': 'المفضلة', 'en': 'Favourites'},
    'cart': {'ar': 'السلة', 'en': 'Cart'},
    'search': {'ar': 'البحث', 'en': 'Search'},
    'filter_orderable': {'ar': 'المتاح للطلب', 'en': 'Orderable'},
    'filter_new': {'ar': 'الجديد', 'en': 'New'},
    'filter_all': {'ar': 'الكل', 'en': 'All'},
    'no_results': {'ar': 'لا توجد نتائج', 'en': 'No results'},
    'no_results_sub': {'ar': 'جرّب كلمة أخرى أو تصفّح الأقسام', 'en': 'Try another word or browse categories'},
    'price_by_selection': {'ar': 'السعر حسب الاختيار', 'en': 'Price by selection'},
    'price_by_selection_long': {
      'ar': 'سعر هذا الصنف يعتمد على الحجم والإضافات، وهي بانتظار اعتماد الإدارة. لا يمكن طلبه حالياً.',
      'en': 'This item is priced by size and add-ons, which are awaiting approval. It cannot be ordered yet.'
    },
    'unavailable': {'ar': 'غير متوفر حالياً', 'en': 'Currently unavailable'},
    'size': {'ar': 'الحجم', 'en': 'Size'},
    'addons': {'ar': 'الإضافات', 'en': 'Add-ons'},
    'notes': {'ar': 'ملاحظات للتحضير', 'en': 'Preparation notes'},
    'notes_hint': {'ar': 'مثال: بدون ثلج', 'en': 'e.g. no ice'},
    'allergens': {'ar': 'معلومات الحساسية', 'en': 'Allergen information'},
    'allergens_pending': {'ar': 'بانتظار الاعتماد — اسأل الفرع قبل الطلب', 'en': 'Awaiting approval — ask the branch before ordering'},
    'illustration_note': {'ar': 'رسم توضيحي — ليس صورة المنتج', 'en': 'Illustration — not a product photo'},
    'add_to_cart': {'ar': 'أضف للسلة', 'en': 'Add to cart'},
    'added_to_cart': {'ar': 'أُضيف للسلة', 'en': 'Added to cart'},
    'view_cart': {'ar': 'عرض السلة', 'en': 'View cart'},
    'cart_empty': {'ar': 'سلتك فاضية', 'en': 'Your cart is empty'},
    'cart_empty_sub': {'ar': 'اختر من المنيو وخلّي مزاجك يقرر', 'en': 'Pick something from the menu'},
    'browse_menu': {'ar': 'تصفّح المنيو', 'en': 'Browse menu'},
    'cart_item_invalid': {'ar': 'هذا الصنف لم يعد متاحاً أو تغيّر سعره', 'en': 'This item is no longer available or its price changed'},
    'checkout': {'ar': 'متابعة الطلب', 'en': 'Checkout'},
    'address': {'ar': 'عنوان التوصيل', 'en': 'Delivery address'},
    'address_hint': {'ar': 'المنطقة، الشارع، المبنى، الشقة', 'en': 'Area, street, building, flat'},
    'maps_off': {'ar': 'الخريطة غير مفعّلة بعد — أدخل العنوان يدوياً', 'en': 'Maps not enabled yet — enter the address manually'},
    'rewards': {'ar': 'القسائم والنقاط', 'en': 'Coupons & points'},
    'coupon_code': {'ar': 'رمز القسيمة', 'en': 'Coupon code'},
    'apply': {'ar': 'تطبيق', 'en': 'Apply'},
    'points_off': {'ar': 'برنامج النقاط لم يُفعّل بعد', 'en': 'Loyalty points are not active yet'},
    'review': {'ar': 'مراجعة الطلب', 'en': 'Review order'},
    'subtotal': {'ar': 'المجموع الفرعي', 'en': 'Subtotal'},
    'discount': {'ar': 'الخصم', 'en': 'Discount'},
    'delivery_fee': {'ar': 'رسوم التوصيل', 'en': 'Delivery fee'},
    'vat_included': {'ar': 'منها ضريبة القيمة المضافة ٥٪', 'en': 'Incl. 5% VAT'},
    'vat_added': {'ar': 'ضريبة القيمة المضافة ٥٪', 'en': 'VAT 5%'},
    'vat_pending': {'ar': 'طريقة احتساب الضريبة بانتظار التأكيد', 'en': 'VAT treatment awaiting confirmation'},
    'total': {'ar': 'الإجمالي', 'en': 'Total'},
    'free': {'ar': 'مجاناً', 'en': 'Free'},
    'test_delivery_fee': {'ar': '٠ د.إ (تجريبي — غير معتمد)', 'en': 'AED 0 (test — not approved)'},
    'place_order': {'ar': 'تأكيد الطلب والدفع', 'en': 'Place order & pay'},
    'payment': {'ar': 'الدفع', 'en': 'Payment'},
    'payments_off': {'ar': 'الدفع الإلكتروني غير مفعّل بعد. هذه محاكاة للاختبار فقط.', 'en': 'Online payment is not active yet. This is a test simulation.'},
    'simulate_pay': {'ar': 'محاكاة دفع ناجح', 'en': 'Simulate successful payment'},
    'payment_failed': {'ar': 'تعذّر إتمام الدفع', 'en': 'Payment failed'},
    'payment_failed_sub': {'ar': 'لم يُخصم أي مبلغ. يمكنك المحاولة مجدداً.', 'en': 'You were not charged. You can try again.'},
    'order_confirmed': {'ar': 'تم! طلبك وصلنا', 'en': 'Done! We got your order'},
    'order_number': {'ar': 'رقم الطلب', 'en': 'Order no.'},
    'track_order': {'ar': 'تتبّع الطلب', 'en': 'Track order'},
    'reorder': {'ar': 'اطلب مجدداً', 'en': 'Reorder'},
    'reorder_changed': {'ar': 'بعض الأصناف لم تعد متاحة وتمت إزالتها', 'en': 'Some items are no longer available and were removed'},
    'no_orders': {'ar': 'ما عندك طلبات بعد', 'en': 'No orders yet'},
    'sign_in': {'ar': 'تسجيل الدخول', 'en': 'Sign in'},
    'sign_in_sub': {'ar': 'سجّل برقم جوالك لإكمال الطلب', 'en': 'Sign in with your mobile to checkout'},
    'phone': {'ar': 'رقم الجوال', 'en': 'Mobile number'},
    'send_code': {'ar': 'أرسل الرمز', 'en': 'Send code'},
    'otp': {'ar': 'رمز التحقق', 'en': 'Verification code'},
    'otp_demo': {'ar': 'نسخة تجريبية: الرمز 123456 ولا تُرسل رسائل حقيقية', 'en': 'Demo: code is 123456, no real SMS is sent'},
    'otp_wrong': {'ar': 'الرمز غير صحيح', 'en': 'Incorrect code'},
    'recover_account': {'ar': 'استعادة الحساب', 'en': 'Recover account'},
    'recover_sub': {'ar': 'غيّرت رقمك؟ تواصل مع الدعم لنقل طلباتك ونقاطك.', 'en': 'Changed your number? Contact support to move your orders and points.'},
    'guest': {'ar': 'زائر', 'en': 'Guest'},
    'sign_out': {'ar': 'تسجيل الخروج', 'en': 'Sign out'},
    'language': {'ar': 'اللغة', 'en': 'Language'},
    'reduce_motion': {'ar': 'تقليل الحركة', 'en': 'Reduce motion'},
    'notifications': {'ar': 'الإشعارات', 'en': 'Notifications'},
    'notifications_empty': {'ar': 'لا توجد إشعارات', 'en': 'No notifications'},
    'notifications_denied': {'ar': 'الإشعارات متوقفة — فعّلها لتصلك حالة طلبك', 'en': 'Notifications are off — enable them for order updates'},
    'enable': {'ar': 'تفعيل', 'en': 'Enable'},
    'support': {'ar': 'الدعم', 'en': 'Support'},
    'support_email_pending': {'ar': 'البريد الرسمي قيد التفعيل', 'en': 'Official e-mail being set up'},
    'rate_order': {'ar': 'قيّم طلبك', 'en': 'Rate your order'},
    'thanks_rating': {'ar': 'شكراً لتقييمك!', 'en': 'Thanks for rating!'},
    'demo_ribbon': {'ar': 'نسخة تجريبية — أسعار مرصودة غير معتمدة', 'en': 'Demo — observed, unapproved prices'},
    'demo_tools': {'ar': 'أدوات الاختبار', 'en': 'Test tools'},
    'offline': {'ar': 'لا يوجد اتصال بالإنترنت', 'en': "You're offline"},
    'offline_sub': {'ar': 'تحقق من الاتصال وحاول مجدداً', 'en': 'Check your connection and try again'},
    'no_offers': {'ar': 'لا توجد عروض معتمدة حالياً', 'en': 'No approved offers right now'},
    'no_offers_sub': {'ar': 'العروض تظهر هنا فور اعتمادها', 'en': 'Offers appear here once approved'},
    'favorites_empty': {'ar': 'لا توجد مفضلة بعد', 'en': 'No favourites yet'},
    'status_pendingPayment': {'ar': 'بانتظار الدفع', 'en': 'Awaiting payment'},
    'status_placed': {'ar': 'تم استلام الطلب', 'en': 'Order received'},
    'status_accepted': {'ar': 'تم قبول الطلب', 'en': 'Accepted'},
    'status_preparing': {'ar': 'جارٍ التحضير', 'en': 'Preparing'},
    'status_ready': {'ar': 'جاهز للاستلام', 'en': 'Ready for pickup'},
    'status_outForDelivery': {'ar': 'في الطريق إليك', 'en': 'On the way'},
    'status_completed': {'ar': 'مكتمل', 'en': 'Completed'},
    'status_cancelled': {'ar': 'ملغى', 'en': 'Cancelled'},
    'status_rejected': {'ar': 'مرفوض', 'en': 'Rejected'},
    'err_OFFLINE': {'ar': 'لا يوجد اتصال بالإنترنت', 'en': "You're offline"},
    'err_BRANCH_CLOSED': {'ar': 'الفرع مغلق الآن، جرّب لاحقاً', 'en': 'The branch is closed now'},
    'err_BRANCH_UNAVAILABLE': {'ar': 'هذا الفرع لا يستقبل الطلبات حالياً', 'en': 'This branch is not taking orders'},
    'err_PRODUCT_UNAVAILABLE': {'ar': 'أحد الأصناف لم يعد متوفراً', 'en': 'An item is no longer available'},
    'err_PRICE_NOT_APPROVED': {'ar': 'سعر أحد الأصناف غير معتمد بعد', 'en': "An item's price isn't approved yet"},
    'err_COUPON_INVALID': {'ar': 'القسيمة غير صالحة أو منتهية', 'en': 'Coupon is invalid or expired'},
    'err_PAYMENT_FAILED': {'ar': 'تعذّر إتمام الدفع', 'en': 'Payment failed'},
    'err_PAYMENTS_DISABLED': {'ar': 'الدفع الإلكتروني غير مفعّل بعد', 'en': 'Online payment is not active yet'},
    'err_DELIVERY_NOT_CONFIGURED': {'ar': 'التوصيل غير مفعّل لهذا الفرع', 'en': 'Delivery is not set up for this branch'},
    'err_EMPTY_CART': {'ar': 'السلة فارغة', 'en': 'Your cart is empty'},
    'err_UNKNOWN': {'ar': 'حدث خطأ غير متوقع', 'en': 'Something went wrong'},
  };
}

extension SContext on BuildContext {
  S get s => S.of(this);
}
