"""Generates backend/supabase/seed.sql from the validated JSON seed.
Everything is inserted as NOT approved:
  - branches: pending_owner_data (no address/phone/hours invented)
  - products: content_status = pending_approval
  - New Shahama observed prices: status = pending_approval, source = talabat_observed
  - dessert offer: draft, no dates (unknown)
The observed menu is linked ONLY to New Shahama (br_04); other branches get nothing.
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
menu = json.load(open(os.path.join(ROOT, 'data', 'seed_menu_new_shahama.json'), encoding='utf-8'))
branches = json.load(open(os.path.join(ROOT, 'data', 'seed_branches.json'), encoding='utf-8'))['branches']
SHAHAMA = next(b['id'] for b in branches if b['name_ar_observed'] == 'الشهامة الجديدة')
SRC = f"talabat_observed_{menu['source']['observed_at']}"


def q(v):
    return 'null' if v is None else "'" + str(v).replace("'", "''") + "'"


out = ['-- GENERATED by tools/build_seed_sql.py — do not edit by hand', 'begin;']
for b in branches:
    out.append(f"insert into branches(id, name_ar, status) values ({q(b['id'])}, {q(b['name_ar_observed'])}, 'pending_owner_data');")
for c in menu['categories']:
    out.append(f"insert into categories(id, sort, name_ar) values ({q(c['id'])}, {c['sort']}, {q(c['name_ar_observed'])});")
    for it in c['items']:
        out.append(f"insert into products(id, category_id, sort, name_ar, price_mode, content_status) values "
                   f"({q(it['id'])}, {q(c['id'])}, {it['sort']}, {q(it['name_ar_observed'])}, '{it['price_mode']}', 'pending_approval');")
        if it['price_mode'] == 'fixed':
            out.append(f"insert into branch_product_prices(branch_id, product_id, price_fils, status, source) values "
                       f"({q(SHAHAMA)}, {q(it['id'])}, {it['base_price_fils']}, 'pending_approval', {q(SRC)});")
offer_items = [it['id'] for c in menu['categories'] for it in c['items'] if it.get('observed_offer')]
if offer_items:
    arr = 'array[' + ','.join(q(i) for i in offer_items) + ']'
    out.append(f"insert into offers(id, title_ar, kind, value, product_ids, branch_ids, status, source) values "
               f"('offer_desserts_observed', 'الحلويات بنصف السعر (مرصود)', 'fixed_price', 2250, {arr}, array[{q(SHAHAMA)}], 'draft', {q(SRC)});")
out.append('commit;')
p = os.path.join(ROOT, 'backend', 'supabase', 'seed.sql')
open(p, 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('wrote', p, len(out) - 3, 'statements; observed prices linked to', SHAHAMA, '; offer items', len(offer_items))
